server:
  port: 8761

spring:
  application:
    name: spring-discovery

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false